config/routes.rb
CETApr::Application.routes.draw do

  resources :students

  resources :academies

  resources :professionals

  resources :course_totals

  resources :sessions,      only: [:new, :create, :destroy]

  resources :import_student_dbf do
    collection do
      get :index, :preview
      post :save
    end
  end

  resources :users do
    collection do
      get :index_student_users
    end
  end

  resources :all_tests do
    collection do
     get :down_load_file
    end
  end

  resources :sign_ups do
    collection do
      get :all_test
      get :last_test
      get :every_test
      get :my_sign_ups
    end
  end

  get "home/menu"
  root to: 'sessions#new'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
end

app/models/all_test.rb
class AllTest < ActiveRecord::Base
  has_one :all_test_course
  has_many :sign_ups
  validates :description, presence: true

  def up_load_file=(up_file)
     self.attachment  = load_file(up_file)
   end


   def load_file(file)
     unless file.original_filename.empty?
       #生成一个随机的文件名
       @filename=get_file_name(file.original_filename)
       #向dir目录写入文件
       File.open("/public/load/#{@filename}", "wb") do |f|
         f.write(file.read)
       end
       #返回文件名称，保存到数据库中
          @filename
     end
   end

   def get_file_name(filename)
     unless filename.nil?
       #filename.sub(/.*./,rand.to_s+'.')
      Time.now.strftime("%Y%m%d%H%M%S")+'_'+filename
     end
   end
end

app/controllers/all_tests_controller.rb
class AllTestsController < ApplicationController
  before_action :set_all_test, only: [:show, :edit, :update, :destroy]
  before_filter :admin_authorize ,:except => [:down_load_file]

  def down_load_file
      unless params[:id].nil?
        example = AllTest.find(params[:id])
        unless example.nil?
          send_file("/public/load/#{example.attachment}",:filename=>example.attachment , :disposition=>"inline")
        end
      else
        render :text=>"fileNotFound"
      end
  end

  def index
    @all_tests = AllTest.paginate(page: params[:page])
  end

  def show
    @one_test_course = AllTestCourse.find(:last,:conditions => [ 'all_test_id = ?', @all_test.id])

    rescue ActiveRecord::RecordNotFound
    logger.error("Attempt to access invalid all_test #{params[:id]}")
    redirect_to :action => 'index'
  end

  def new
    @all_test = AllTest.new
    @courses=CourseTotal.all
  end

  def edit
    @courses=CourseTotal.all
  end

  def create
    @all_test = AllTest.new(all_test_params)

    respond_to do |format|
      if @all_test.save
        @selected = params[:selected]
        course_encode = @selected.join(";")
        all_test_course = AllTestCourse.new     #具体一次报名考试可以申报的所有课程
        all_test_course.all_test_id = @all_test.id
        all_test_course.course_encode = course_encode
        all_test_course.save
        format.html { redirect_to @all_test, notice: 'All test was successfully created.' }
        format.json { render action: 'show', status: :created, location: @all_test }
      else
        format.html { render action: 'new' }
        format.json { render json: @all_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /all_tests/1
  # PATCH/PUT /all_tests/1.json
  def update
    respond_to do |format|
      if @all_test.update(all_test_params)
        @selected=params[:selected]
        course_encode = @selected.join(";")
        all_test_course = AllTestCourse.find(:last,:conditions => [ 'all_test_id=?', @all_test.id])
        all_test_course.all_test_id = @all_test.id
        all_test_course.course_encode = course_encode
        all_test_course.save
        format.html { redirect_to @all_test, notice: 'All test was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @all_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /all_tests/1
  # DELETE /all_tests/1.json
  def destroy
    @all_test_course = AllTestCourse.where("all_test_id = ?", @all_test.id).first
    @all_test_course.destroy
    @all_test.destroy
    respond_to do |format|
      format.html { redirect_to all_tests_url }
      format.json { head :no_content }
    end
  end

  private
    def set_all_test
      @all_test = AllTest.find(params[:id])
    end

    def all_test_params
      params.require(:all_test).permit(:test_date, :begin_date, :end_date, :description, :attachment)
    end
end

app/helpers/all_tests_helper.rb
module AllTestsHelper
end

app/views/all_tests/_form.html.erb
<%= form_for(@all_test) do |f| %>
  <% if @all_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@all_test.errors.count, "error") %> prohibited this all_test from being saved:</h2>

      <ul>
        <% @all_test.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
      <div class="span6 offset3">
          请选择本次考试所有科目<br>
          <% @courses.each do |course| %>
             <%= h course.course_name %>
             <%= check_box_tag 'selected[]', course.course_encode %>
          <% end %><br>

          <%= f.label :description,"考试简述" %>
          <%= f.text_field :description %>

          <%= f.label :test_date,"考试时间" %>
          <%= f.date_select :test_date,:use_month_numbers=>true %>

          <%= f.label :begin_date,"报名开始时间" %>
          <%= f.date_select :begin_date,:use_month_numbers=>true %>

          <%= f.label :end_date,"报名截止时间" %>
          <%= f.date_select :end_date,:use_month_numbers=>true %>

          <%= f.label :attachment,"附件" %>
          <%= f.file_field :up_load_file %>

          <br>
          <%= f.submit "保存", class: "btn btn-primary" %>
         </div>
       </div>
<% end %>

app/views/all_tests/edit.html.erb
<% provide(:title, "修改考试信息") %>
<h1>修改考试信息</h1>

<%= render 'form' %>

<div class="offset2">
  <%= link_to '显示', @all_test %> |
  <%= link_to '返回', all_tests_path %>
</div>

app/views/all_tests/index.html.erb
<% provide(:title, '历次考试信息') %>
<h1>历次考试信息</h1>

<div>
  <%= link_to ">>发布新考试", new_all_test_path,
                                class: "btn btn-large btn-primary btn-link" %>
</div>

<div class="users">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>考试简述</th>
        <th>考试日期</th>
        <th>报名开始日期</th>
        <th>报名截止日期</th>
        <th>附件</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @all_tests.each do |all_test| %>
      <tr>
        <td><%= link_to all_test.description, all_test %></td>
        <td><%= all_test.test_date %></td>
        <td><%= all_test.begin_date %></td>
        <td><%= all_test.end_date %></td>
        <td><% unless all_test.attachment.nil? %>
            <%= link_to '考试附件下载' ,:action => 'down_load_file',:id => all_test.id%>
            <% end %></td>
        <td><%= link_to '修改', edit_all_test_path(all_test) %></td>
        <td><%= link_to '删除', all_test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/all_tests/new.html.erb
<% provide(:title, "新建考试信息") %>
<h1>新建考试信息</h1>

<%= render 'form' %>

<div class="offset2">
  <%= link_to '返回', all_tests_path %>
</div>

app/views/all_tests/show.html.erb
<% provide(:title, '考试信息显示') %>
<h1>本次考试信息</h1>

<div class="row">
  <div class="span6 offset3">
    <p id="notice"><%= notice %></p>
    <p>
      <strong>考试简述:</strong>
      <%= @all_test.description %><br>
    </p>
    <p>
      <strong>考试科目:</strong>
      <%= @one_test_course.course_encode %>
    </p>
    <p>
      <strong>考试日期:</strong>
      <%= @all_test.test_date %>
    </p>
    <p>
      <strong>报名开始日期:</strong>
      <%= @all_test.begin_date %>
    </p>
    <p>
      <strong>报名截止日期:</strong>
      <%= @all_test.end_date %>
    </p>
    <p>
      <strong>考试附件下载:</strong>
      <% unless @all_test.attachment.nil? %>
      <%= link_to '本次考试附件下载' ,:action => 'down_load_file',:id => @all_test.id%>
      <% end %>
    </p>
  </div>
</div>

<div class="offset2">
  <%= link_to '修改', edit_all_test_path(@all_test) %> |
  <%= link_to '返回', all_tests_path %>
</div>