config/routes.rb
CETApr::Application.routes.draw do

  resources :students

  resources :academies

  resources :professionals

  resources :course_totals

  resources :sessions,      only: [:new, :create, :destroy]

  resources :import_student_dbf do
    collection do
      get :index, :preview
      post :save
    end
  end

  resources :users do
    collection do
      get :index_student_users
    end
  end

  resources :all_tests do
    collection do
     get :down_load_file
    end
  end

  resources :sign_ups do
    collection do
      get :all_test
      get :last_test
      get :every_test
      get :my_sign_ups
    end
  end

  get "home/menu"
  root to: 'sessions#new'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
end

app/models/academy.rb
class Academy < ActiveRecord::Base
  validates :academy_encode, presence: true
  validates :academy_name, presence: true
end

app/controllers/academies_controller.rb
class AcademiesController < ApplicationController
  before_action :set_academy, only: [:show, :edit, :update, :destroy]
  before_filter :admin_authorize

  def index
    @academies = Academy.paginate(page: params[:page])
  end

  def show
  end

  def new
    @academy = Academy.new
  end

  def edit
  end

  def create
    @academy = Academy.new(academy_params)

    respond_to do |format|
      if @academy.save
        format.html { redirect_to @academy, notice: 'Academy was successfully created.' }
        format.json { render action: 'show', status: :created, location: @academy }
      else
        format.html { render action: 'new' }
        format.json { render json: @academy.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @academy.update(academy_params)
        format.html { redirect_to @academy, notice: 'Academy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @academy.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @academy.destroy
    respond_to do |format|
      format.html { redirect_to academies_url }
      format.json { head :no_content }
    end
  end

  private
    def set_academy
      @academy = Academy.find(params[:id])
    end

    def academy_params
      params[:academy]
    end
end

app/helpers/academies_helper.rb
module AcademiesHelper
end

app/views/academies/_form.html.erb
<%= form_for(@academy) do |f| %>
  <% if @academy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@academy.errors.count, "error") %> prohibited this academy from being saved:</h2>

      <ul>
        <% @academy.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
      <div class="span6 offset3">
          <%= f.label :academy_encode,"学院代码" %>
          <%= f.text_field :academy_encode %>
 
          <%= f.label :academy_name,"学院名称" %>
          <%= f.text_field :academy_name %>
 
          <%= f.submit "保存", class: "btn btn-primary" %>
      </div>
    </div>
 <% end %>

app/views/academies/edit.html.erb
<% provide(:title, "院系修改") %>
<h1>院系修改</h1>

<%= render 'form' %>

<div class="offset2">
  <%= link_to '显示', @academy %> |
  <%= link_to '返回', professionals_path %>
</div>

app/views/academies/index.html.erb
<% provide(:title, '学院列表') %>
<h1>学院列表</h1>

<div>
  <%= link_to ">>添加学院", new_academy_path,
                                class: "btn btn-large btn-primary btn-link" %>
</div>

<div class="users">
  <table class="table table-striped table-bordered table-hover">
     <tr>
        <th>学院代码</th>
        <th>学院名称</th>
        <th colspan="2">操作</th>
     </tr>
   <% @academies.each do |academy| %>
     <tr>
        <th><%= link_to academy.academy_encode, academy %></th>
        <th><%= link_to academy.academy_name, academy %></th>
        <th><%= link_to "修改", edit_academy_path(academy)%></th>
        <th><%= link_to "删除", academy, method: :delete,
                                 data: { confirm: "确定删除?" } %></th>
     </tr>
   <% end %>
  </table>
</div>

<%= will_paginate %>

app/views/academies/new.html.erb
<% provide(:title, "学院添加") %>
<h1>学院添加</h1>

<%= render 'form' %>

<div class="offset2">
  <%= link_to '返回', academies_path %>
</div>

app/views/academies/show.html.erb
<% provide(:title, @academy.academy_name) %>
<h1>学院显示</h1>

<div class="row">
  <div class="span6 offset3">
    <p id="notice"><%= notice %></p>
    <p>
      <strong>学院代码:</strong>
      <%= @academy.academy_encode %><br>
    </p>
    <p>
      <strong>学院名称:</strong>
      <%= @academy.academy_name %>
    </p>
  </div>
</div>

<div class="offset2">
  <%= link_to '修改', edit_academy_path(@academy) %> |
  <%= link_to '返回', academies_path %>
</div>