config/routes.rb
CETApr::Application.routes.draw do

  resources :students

  resources :academies

  resources :professionals

  resources :course_totals

  resources :sessions,      only: [:new, :create, :destroy]

  resources :import_student_dbf do
    collection do
      get :index, :preview
      post :save
    end
  end

  resources :users do
    collection do
      get :index_student_users
    end
  end

  resources :all_tests do
    collection do
     get :down_load_file
    end
  end

  resources :sign_ups do
    collection do
      get :all_test
      get :last_test
      get :every_test
      get :my_sign_ups
    end
  end

  get "home/menu"
  root to: 'sessions#new'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
end

app/models/academy.rb
class Academy < ActiveRecord::Base
  validates :academy_encode, presence: true
  validates :academy_name, presence: true
end

app/models/all_test.rb
class AllTest < ActiveRecord::Base
  has_one :all_test_course
  has_many :sign_ups
  validates :description, presence: true

  def up_load_file=(up_file)
     self.attachment  = load_file(up_file)
   end


   def load_file(file)
     unless file.original_filename.empty?
       #生成一个随机的文件名
       @filename=get_file_name(file.original_filename)
       #向dir目录写入文件
       File.open("/public/load/#{@filename}", "wb") do |f|
         f.write(file.read)
       end
       #返回文件名称，保存到数据库中
          @filename
     end
   end

   def get_file_name(filename)
     unless filename.nil?
       #filename.sub(/.*./,rand.to_s+'.')
      Time.now.strftime("%Y%m%d%H%M%S")+'_'+filename
     end
   end
end

app/models/all_test_course.rb
class AllTestCourse < ActiveRecord::Base
    belongs_to :all_test
end

app/models/course_total.rb
class CourseTotal < ActiveRecord::Base
  validates :course_encode, presence: true
  validates :course_name, presence: true
end

app/models/professional.rb
class Professional < ActiveRecord::Base
  validates :professional_encode, presence: true
  validates :professional_name, presence: true
end

app/models/sign_up.rb
class SignUp < ActiveRecord::Base
  belongs_to :all_test
  validates :subject_1_encode, presence: true
  validates :tel, presence: true ,length:{is: 11}
  validates :class_name, presence: true
  validates :name, presence: true
  validates :student_no, presence: true
  validates :id_number, presence: true
  validates :grade, presence: true
  #validates :photo_url, presence: true
  #validates_format_of :photo_url,
  #                    :with => %r{\.(jpg|JPG)$}i,
  #                    :message => '必须为.jpg格式'


  def up_load_file=(up_file)
    self.photo_url=load_file(up_file)
  end


  def load_file(file)
    if !file.original_filename.empty?
      #生成一个随机的文件名
      @filename=get_file_name(file.original_filename)
      #向dir目录写入文件
      File.open("/public/photos/#{@filename}", "wb") do |f|
        f.write(file.read)
      end
      #返回文件名称，保存到数据库中
      @filename
    end
  end

  def get_file_name(filename)
    if !filename.nil?
      #filename.sub(/.*./,rand.to_s+'.')
      p student_no
       self.name + File.extname(filename)
    end
  end

  def file_delete(name)
    if File.exist?("#{File.dirname(__FILE__)}/#{name}")
      File.delete("#{File.dirname(__FILE__)}/#{name}")
    end
  end

end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :student_no, presence: true
  validates :name, presence: true
  validates :grade, presence: true
  validates :id_number, presence: true
  validates :academy_encode, presence: true
  validates :professional_encode, presence: true
  validates :gender, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  validates :encode, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password
  #validates :password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end


  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authorize
  def menu
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :admin_authorize


  def index
    @users = User.where("permission != ?", "student_user").paginate(page: params[:page]).order("academy_encode ASC")
  end


  def index_student_users
    @users = User.where('permission = ?', 'student_user').paginate(page: params[:page]).order('academy_encode DESC')
  end

  def show
  end


  def new
    @user = User.new
  end


  def edit
  end


  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "用户创建成功"
      redirect_to users_url
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:encode, :name, :academy_encode,
                                   :password, :password_confirmation,
                                   :remember_token, :permission)
    end
end

app/helpers/academies_helper.rb
module AcademiesHelper
end

app/helpers/all_tests_helper.rb
module AllTestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "考试报名系统"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def get_name_by_paid(code)
    if code=="YES"  then ret="已缴"
      else ret="未缴费"
    end
     ret
  end

  def get_name_by_permission(code)
    unless code.nil?
     if code == "school_admin" then ret = "校管理员"
     elsif code == "academy_admin" then ret = "院管理员"
     elsif  code == "student_user" then ret = "学生用户"
     else ret = "其它"
     end
        ret
    end
    end

end

app/helpers/course_totals_helper.rb
module CourseTotalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/sign_ups_helper.rb
module SignUpsHelper
  def options_for_select_years
    t=Time.now
    t.year
    str_year=t.strftime('%Y')
    year=Integer(str_year)
    years = Hash.new
    (year-5..year+1).each { |i| years.store(i.to_s+"年", i.to_s[2,3]) } #循环赋值给hash
    p years
    years=years.sort{|a,b| a[1] <=> b[1]}  #hash的排序，排序方法不明。后面是倒转，含义不明
    options_for_select(years,year.to_s)
  end

  def options_for_select_grade
     t=Time.now
     t.year
     str_year=t.strftime('%Y')
     year=Integer(str_year)
     years = Hash.new
     (year-5..year+1).each { |i| years.store(i.to_s+"级", i.to_s[2,3]) } #循环赋值给hash
     p years
     years=years.sort{|a,b| a[1] <=> b[1]}  #hash的排序，排序方法不明。后面是倒转，含义不明
     options_for_select(years,year.to_s)
   end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_academy_admin_left.html.erb
<div class="row">
  <div class="pull-right">
     <ul class="nav nav-tabs nav-stacked">
       <li><%= link_to '首页' %></li>
       <li><%= link_to '最近报名情况', last_test_sign_ups_path %> </li>
       <li><%= link_to '历次报名情况', all_test_sign_ups_path %> </li>
       <li><%= link_to '学生账户管理' ,index_student_users_users_path%></li>
       <li><%= link_to '学生信息管理', students_path %> </li>
     </ul>
  </div>
</div>

app/views/layouts/_school_admin_left.html.erb
<div class="row">
  <div class="pull-right">
     <ul class="nav nav-tabs nav-stacked">
       <li><%= link_to '首页' %></li>
       <li><%= link_to '学院管理', academies_path %></li>
       <li><%= link_to '专业管理', professionals_path %></li>
       <li><%= link_to '考试科目管理', course_totals_path %></li>
       <li><%= link_to '考试报名信息发布', all_tests_path%></li>
       <li><%= link_to '最近报名情况', last_test_sign_ups_path %> </li>
       <li><%= link_to '历次报名情况', all_test_sign_ups_path %> </li>
       <li><%= link_to '管理员账户管理', users_path %></li>
       <li><%= link_to '学生账户管理' ,index_student_users_users_path%></li>
       <li><%= link_to '新生学籍导入' %></li>
       <li><%= link_to '学生信息管理', students_path %> </li>
     </ul>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_student_user_left.html.erb
<div class="row">
  <div class="pull-right">
     <ul class="nav nav-tabs nav-stacked">
       <li><%= link_to '首页' %></li>
       <li><%= link_to '个人报名', new_sign_up_path %></li>
       <li><%= link_to '查看历史报名信息', my_sign_ups_sign_ups_path %> </li>
       <li><%= link_to '个人信息错误申请修改' %></li>
     </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", 
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <% if signed_in? %>
              <div class="pull-right">
                    <h4><%= current_user.encode %></h4>
                    <h4><%= current_user.academy_encode %></h4>
                    <h4><%= get_name_by_permission(current_user.permission) %></h4>
                    <h4><%= link_to "修改密码", edit_user_path(current_user) %></h4>
                    <h4><%= link_to "退出登录", signout_path, method: "delete" %></h4>
                    <h4>-------------------</h4>
                 <% if current_user.permission == "school_admin" %>
                    <%= render 'layouts/school_admin_left' %>
                 <% elsif current_user.permission == "academy_admin" %>
                    <%= render 'layouts/academy_admin_left' %>
                 <% elsif current_user.permission == "student_user" %>
                    <%= render 'layouts/student_user_left' %>
                 <% end %>
              </div>
          <% end %>
        </div>
        <div class="span10">
            <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>"><%= value %></div>
            <% end %>
            <%= yield %>
            <% #debug(params) if Rails.env.development? %>
          </div>
        </div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>